# Change these first
owner: digital-land # Your GitHub organization or username, where this repository lives
repo: service-status # The name of this repository

sites:
  - name: Platform Website
    url: https://www.planning.data.gov.uk
  - name: Query API
    url: https://datasette.planning.data.gov.uk
  - name: Map Tiles API
    url: https://datasette-tiles.planning.data.gov.uk
  - name: Internal Status API
    url: https://status.planning.data.gov.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: service-status.planning.data.gov.uk
  #  baseUrl: /service-status
  logoUrl: https://raw.githubusercontent.com/digital-land/digital-land.info/main/assets/images/favicon.svg
  name: Planning Data Service Status
  introTitle: Planning Data aims to make land and housing data easier to find, understand, use and trust.
  introMessage: |
    Our platform collects planning and housing data from local planning authorities (LPAs) and transforms it into a 
    consistent state, across England. Anyone can view, download and analyse the data we hold.
  navbar:
    - title: Platform
      href: https://www.planning.data.gov.uk
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
